/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movie.rental.system.project;
import java.util.*;
import java.io.PrintWriter;
import java.io.FileOutputStream;
import java.io.FileNotFoundException;
import javax.swing.JOptionPane;
/**
 *
 * @author Abbas Zaheer
 */
public class AddMovieRecord extends javax.swing.JFrame {

    /**
     * Creates new form AddMovieRecord
     */
    
     
     ArrayList<String> TempStarList= new ArrayList<String>();
     
    public AddMovieRecord() {
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox();
        P_Head1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Back_Button = new javax.swing.JButton();
        Container = new javax.swing.JPanel();
        L_Name = new javax.swing.JLabel();
        L_Year = new javax.swing.JLabel();
        L_Stars = new javax.swing.JLabel();
        L_Category = new javax.swing.JLabel();
        L_Copies = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        B_MoreStars = new javax.swing.JButton();
        FamousStarJ = new javax.swing.JComboBox();
        YearJ = new javax.swing.JComboBox();
        CategoryJ = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        B_SaveRecord = new javax.swing.JButton();
        B_Clear = new javax.swing.JButton();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        P_Head1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/rental/system/project/Add List_32px.png"))); // NOI18N
        jLabel7.setText("Add a Movie Record");

        javax.swing.GroupLayout P_Head1Layout = new javax.swing.GroupLayout(P_Head1);
        P_Head1.setLayout(P_Head1Layout);
        P_Head1Layout.setHorizontalGroup(
            P_Head1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_Head1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addGap(63, 63, 63))
        );
        P_Head1Layout.setVerticalGroup(
            P_Head1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_Head1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        Back_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/rental/system/project/Go Back_24px.png"))); // NOI18N
        Back_Button.setText("Back");
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });

        Container.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        L_Name.setText("Name of Movie *");

        L_Year.setText("Year of Release *");

        L_Stars.setText("Stars");

        L_Category.setText("Category");

        L_Copies.setText("Number of Copies *");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        B_MoreStars.setText("Add More");
        B_MoreStars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_MoreStarsActionPerformed(evt);
            }
        });

        FamousStarJ.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Salman Khan", "Shah Rukh Khan", "Aamir Khan", "Dharmendra", "Akshay Kumar", "Ashok Kumar", "Sunil Dutt", "Sanjeev Kumar", "Ajay Devgn", "Naseeruddin Shah", "Anil Kapoor", "Sanjay Dutt", "Vinod Khanna", "Nana Patekar", "Shammi Kapoor", "Sunny Deol", "Mithun Chakraborty", "Johnny Depp", "Al Pacino", "Robert De Niro", "Kevin Spacey", "Russell Crowe", "Angelina Jolie", "Brad Pitt", "Leonardo DiCaprio", "Arnold Schwarzenegger", "Tom Cruise", "Sylvester Stallone", "Morgan Freeman", "Nicolas Cage" }));
        FamousStarJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FamousStarJActionPerformed(evt);
            }
        });

        YearJ.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950" }));
        YearJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearJActionPerformed(evt);
            }
        });

        CategoryJ.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Genre", "Action", "Adventure", "Animation", "Biography", "Comedy", "Crime", "Documentary", "Drama", "Family", "Fantasy", "Film Noir", "History", "Horror", "Music", "Musical", "Mystery", "Romance", "Sci-Fi", "Sport", "Superhero", "Thriller", "War" }));
        CategoryJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryJActionPerformed(evt);
            }
        });

        jLabel1.setText("OR");

        jLabel2.setText("OR");

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addComponent(L_Copies)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField5))
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_Name)
                            .addComponent(L_Year)
                            .addComponent(L_Stars)
                            .addComponent(L_Category))
                        .addGap(27, 27, 27)
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContainerLayout.createSequentialGroup()
                                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ContainerLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(YearJ, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(ContainerLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(FamousStarJ, 0, 1, Short.MAX_VALUE)
                                            .addGroup(ContainerLayout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(CategoryJ, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                            .addComponent(jTextField1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_MoreStars)
                .addContainerGap())
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_Name)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_Year)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YearJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(17, 17, 17)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(L_Stars)
                        .addComponent(B_MoreStars)
                        .addComponent(FamousStarJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_Category)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CategoryJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_Copies)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        B_SaveRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/rental/system/project/Save_24px.png"))); // NOI18N
        B_SaveRecord.setText("Save Record");
        B_SaveRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_SaveRecordActionPerformed(evt);
            }
        });

        B_Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/rental/system/project/Erase_24px.png"))); // NOI18N
        B_Clear.setText("Clear");
        B_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P_Head1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(B_SaveRecord)
                        .addGap(18, 18, 18)
                        .addComponent(B_Clear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Back_Button)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(P_Head1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back_Button)
                    .addComponent(B_SaveRecord)
                    .addComponent(B_Clear))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_Back_ButtonActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void B_SaveRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_SaveRecordActionPerformed
       if(jTextField1.getText().equals("") || (jTextField2.getText().equals("") && YearJ.getItemCount() == 0) || jTextField5.getText().equals(""))
       {
           JOptionPane.showMessageDialog(this,"Please Enter Compulsery Fields !");
       }
       else
       {
        String NAME= jTextField1.getText();
        
        String YEAR;
        
        if(YearJ.getItemCount() == 0)
        {
            YEAR = jTextField2.getText();
        
        }
        else
        {
            YEAR=YearJ.getSelectedItem().toString();
            jTextField2.setText(YEAR);
        }
        
        //Stars List Top
        String LASTSTAR;
        
        
        if(CategoryJ.getItemCount() == 0)
        {
            LASTSTAR= jTextField3.getText();
        
        }
        else
        {
            LASTSTAR=FamousStarJ.getSelectedItem().toString();
        }

        
        TempStarList.add(LASTSTAR);
        //Last Star List
        String CATEGORY;
        
        if(CategoryJ.getItemCount() == 0)
        {
            CATEGORY= jTextField4.getText();
        
        }
        else
        {
            CATEGORY=CategoryJ.getSelectedItem().toString();
        }
        
        int COPIES= Integer.parseInt(jTextField5.getText());
        
        if(COPIES<=0)
        {
            JOptionPane.showMessageDialog(this,"Please Enter Valid No. of Copies !");
        }
        else
        {
                Movie MovieObj = new Movie(NAME,YEAR,TempStarList,CATEGORY,COPIES);

            PrintWriter fout=null;

            try
            {
                fout = new PrintWriter(new FileOutputStream("Movies.txt",true));

                fout.println("~Data~");
                fout.println(NAME);
                fout.println(YEAR);
                    fout.println("*Stars*");
                for(String i: TempStarList)
                {
                    fout.println(i);
                }
                    fout.println("*/Stars*");

                fout.println("\n"+CATEGORY);
                fout.println(COPIES);
                fout.println("~/Data~");
            }
            catch(FileNotFoundException e)
            {
                System.out.println("Error in Opening File");
            }
            fout.close();
            JOptionPane.showMessageDialog(this,"Record is Added");
        }
        }
        
        
        
        
        
    }//GEN-LAST:event_B_SaveRecordActionPerformed

    private void B_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ClearActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        TempStarList.clear();
    }//GEN-LAST:event_B_ClearActionPerformed

    private void B_MoreStarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_MoreStarsActionPerformed
        String Star = jTextField3.getText();
        TempStarList.add(Star);
        jTextField3.setText("");
    }//GEN-LAST:event_B_MoreStarsActionPerformed

    private void FamousStarJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FamousStarJActionPerformed
        jTextField3.setText(FamousStarJ.getSelectedItem().toString());
    }//GEN-LAST:event_FamousStarJActionPerformed

    private void YearJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearJActionPerformed
        jTextField2.setText(YearJ.getSelectedItem().toString());
    }//GEN-LAST:event_YearJActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
       
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void CategoryJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryJActionPerformed
        jTextField4.setText(CategoryJ.getSelectedItem().toString());
    }//GEN-LAST:event_CategoryJActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMovieRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMovieRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMovieRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMovieRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMovieRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Clear;
    private javax.swing.JButton B_MoreStars;
    private javax.swing.JButton B_SaveRecord;
    private javax.swing.JButton Back_Button;
    private javax.swing.JComboBox CategoryJ;
    private javax.swing.JPanel Container;
    private javax.swing.JComboBox FamousStarJ;
    private javax.swing.JLabel L_Category;
    private javax.swing.JLabel L_Copies;
    private javax.swing.JLabel L_Name;
    private javax.swing.JLabel L_Stars;
    private javax.swing.JLabel L_Year;
    private javax.swing.JPanel P_Head1;
    private javax.swing.JComboBox YearJ;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
