/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movie.rental.system.project;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.*;
/**
 *
 * @author Abbas Zaheer
 */
public class ExistingCustomer extends javax.swing.JFrame {

    /**
     * Creates new form ExistingCustomer
     */
    
    public ExistingCustomer() {
        initComponents();
        
        
        jTextArea1.append("Username"+"\t"+"Name"+"\t\t"+"ID Card"+"\t\t"+"Phone No"+"\t\t"+"Email"+"\n\n");
        
         Scanner fin = null;

                try
                {
                    fin = new Scanner(new FileInputStream("Customer.txt"));
                    String Username,Name,IdNo,PhoneNo,Email;
                    
                    
                    while(fin.hasNextLine())
                    {
                        String s[][] = new String[1][5];
                        int i=0;
                        String line=fin.nextLine();
                        while(!line.contains("~/Info~"))
                        {
                            Username=fin.nextLine();
                            //System.out.println(Username);
                            s[i][0]=Username;
                            
                            Name=fin.nextLine();
                            //System.out.println(Name);
                            s[i][1]=Name;
                            
                            IdNo=fin.nextLine();
                            //System.out.println(IdNo);
                            s[i][2]=IdNo;
                            
                            PhoneNo=fin.nextLine();
                            //System.out.println(PhoneNo);
                            s[i][3]=PhoneNo;
                            
                            Email=fin.nextLine();
                            //System.out.println("Email : "+Email);
                            s[i][4]=Email;
                                                        
                                                        
                            jTextArea1.append(s[i][0]+"\t"+s[i][1]+"\t\t"+s[i][2]+"\t"+s[i][3]+"\t\t"+s[i][4]+"\n");
                            
                            line=fin.nextLine();
                            //i++;
                        }
                        
                        
                        
                        
                       
                    }

                    
                    
                }
                catch(FileNotFoundException e)
                {
                    System.out.println("Error in Opening File");
                }
                fin.close();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        P_Head1 = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        Proceed = new javax.swing.JButton();
        Back_Button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        P_Head2 = new javax.swing.JPanel();
        heading1 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        P_Head1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        heading.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading.setText("Enter Username");

        UsernameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Proceed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/rental/system/project/Export_24px.png"))); // NOI18N
        Proceed.setText("Proceed");
        Proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProceedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout P_Head1Layout = new javax.swing.GroupLayout(P_Head1);
        P_Head1.setLayout(P_Head1Layout);
        P_Head1Layout.setHorizontalGroup(
            P_Head1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_Head1Layout.createSequentialGroup()
                .addGroup(P_Head1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_Head1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_Head1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Proceed)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        P_Head1Layout.setVerticalGroup(
            P_Head1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_Head1Layout.createSequentialGroup()
                .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P_Head1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Proceed)
                    .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        Back_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/rental/system/project/Go Back_24px.png"))); // NOI18N
        Back_Button.setText("Back");
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        P_Head2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        heading1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        heading1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/rental/system/project/User Account_32px.png"))); // NOI18N
        heading1.setText("Existing Customers Record");

        javax.swing.GroupLayout P_Head2Layout = new javax.swing.GroupLayout(P_Head2);
        P_Head2.setLayout(P_Head2Layout);
        P_Head2Layout.setHorizontalGroup(
            P_Head2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_Head2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(heading1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addGap(63, 63, 63))
        );
        P_Head2Layout.setVerticalGroup(
            P_Head2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_Head2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(heading1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(P_Head1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Back_Button)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(P_Head2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(P_Head1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(Back_Button)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(P_Head2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(329, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_Back_ButtonActionPerformed

    private void ProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProceedActionPerformed
        
        String Username = UsernameTextField.getText();
        
                Scanner fin = null;

                try
                {
                    fin = new Scanner(new FileInputStream("Customer.txt"));
                    //String Username,Name,IdNo,PhoneNo,Email;
                    boolean Login=false;
                                        
                    while(fin.hasNextLine())
                    {
                        String line = fin.nextLine();
                       
                        if(line.contains(Username))
                        {
                            Login=true;
                            JOptionPane.showMessageDialog(this, "Logged in Successfully"); 
                            CustomerMenu Obj = new CustomerMenu();
                            Obj.setVisible(true);
                            //break;
                        }
                    }
                    if(Login==false)
                                    {
                                        JOptionPane.showMessageDialog(this, "Not Found !"); 
                                    }
                            
                }
                catch(FileNotFoundException e)
                {
                                System.out.println("Error in Opening File");
                }
                fin.close();
    }//GEN-LAST:event_ProceedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExistingCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExistingCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExistingCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExistingCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExistingCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Button;
    private javax.swing.JPanel P_Head1;
    private javax.swing.JPanel P_Head2;
    private javax.swing.JButton Proceed;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel heading1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
