/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movie.rental.system.project;
import java.util.*;
/**
 *
 * @author Abbas Zaheer
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    private ArrayList <Movie> MoviesList;
    
    public MainMenu() {
        initComponents();
        MoviesList = new ArrayList<Movie>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P_Left = new javax.swing.JPanel();
        L_MovieArea = new javax.swing.JLabel();
        B_SearchMovie = new javax.swing.JButton();
        B_ShowMovies = new javax.swing.JButton();
        B_AddMovies = new javax.swing.JButton();
        B_EditMovie = new javax.swing.JButton();
        B_DeleteMovie = new javax.swing.JButton();
        P_Right = new javax.swing.JPanel();
        L_CustomerArea = new javax.swing.JLabel();
        B_AddCustomer = new javax.swing.JButton();
        B_ExistingCustomer = new javax.swing.JButton();
        B_DeleteCustomer = new javax.swing.JButton();
        P_Head = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Exit_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        P_Left.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        L_MovieArea.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        L_MovieArea.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        L_MovieArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/rental/system/project/DVD Logo_32px.png"))); // NOI18N
        L_MovieArea.setText("Movie");

        B_SearchMovie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/rental/system/project/View_24px.png"))); // NOI18N
        B_SearchMovie.setText("Search a Movie");
        B_SearchMovie.setToolTipText("");
        B_SearchMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_SearchMovieActionPerformed(evt);
            }
        });

        B_ShowMovies.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/rental/system/project/More Details_24px.png"))); // NOI18N
        B_ShowMovies.setText("Show All Movies");
        B_ShowMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ShowMoviesActionPerformed(evt);
            }
        });

        B_AddMovies.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/rental/system/project/Add Property_24px.png"))); // NOI18N
        B_AddMovies.setText("Add a Movie Record");
        B_AddMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_AddMoviesActionPerformed(evt);
            }
        });

        B_EditMovie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/rental/system/project/Edit Property_24px.png"))); // NOI18N
        B_EditMovie.setText("Edit a Movie Record");

        B_DeleteMovie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/rental/system/project/Waste_24px.png"))); // NOI18N
        B_DeleteMovie.setText("Delete a Movie Record");
        B_DeleteMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_DeleteMovieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout P_LeftLayout = new javax.swing.GroupLayout(P_Left);
        P_Left.setLayout(P_LeftLayout);
        P_LeftLayout.setHorizontalGroup(
            P_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_LeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_MovieArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_SearchMovie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_ShowMovies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_AddMovies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_EditMovie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_DeleteMovie, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                .addContainerGap())
        );
        P_LeftLayout.setVerticalGroup(
            P_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_LeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_MovieArea, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(B_SearchMovie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_ShowMovies)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_AddMovies)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_EditMovie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_DeleteMovie)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        P_Right.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        L_CustomerArea.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        L_CustomerArea.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        L_CustomerArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/rental/system/project/Queue_32px.png"))); // NOI18N
        L_CustomerArea.setText("Customer");

        B_AddCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/rental/system/project/Add User Male_24px.png"))); // NOI18N
        B_AddCustomer.setText("Add a New Customer");
        B_AddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_AddCustomerActionPerformed(evt);
            }
        });

        B_ExistingCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/rental/system/project/User Groups_24px.png"))); // NOI18N
        B_ExistingCustomer.setText("Existing Customers");
        B_ExistingCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ExistingCustomerActionPerformed(evt);
            }
        });

        B_DeleteCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/rental/system/project/Waste_24px.png"))); // NOI18N
        B_DeleteCustomer.setText("Delete a Customer");

        javax.swing.GroupLayout P_RightLayout = new javax.swing.GroupLayout(P_Right);
        P_Right.setLayout(P_RightLayout);
        P_RightLayout.setHorizontalGroup(
            P_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_RightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_AddCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(L_CustomerArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_ExistingCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_DeleteCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        P_RightLayout.setVerticalGroup(
            P_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_RightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_CustomerArea, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(B_AddCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_ExistingCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_DeleteCustomer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        P_Head.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/rental/system/project/Movie Projector_32px.png"))); // NOI18N
        jLabel1.setText("Movie Rental System");

        javax.swing.GroupLayout P_HeadLayout = new javax.swing.GroupLayout(P_Head);
        P_Head.setLayout(P_HeadLayout);
        P_HeadLayout.setHorizontalGroup(
            P_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_HeadLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(78, 78, 78))
        );
        P_HeadLayout.setVerticalGroup(
            P_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_HeadLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        Exit_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/rental/system/project/Shutdown_24px.png"))); // NOI18N
        Exit_Button.setText("Exit");
        Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P_Head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(P_Left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(P_Right, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Exit_Button)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(P_Head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(P_Left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(P_Right, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Exit_Button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_ShowMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ShowMoviesActionPerformed
        ShowAllMovies Obj = new ShowAllMovies();
        Obj.setVisible(true);
    }//GEN-LAST:event_B_ShowMoviesActionPerformed

    private void Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_ButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_Exit_ButtonActionPerformed

    private void B_DeleteMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_DeleteMovieActionPerformed
        DeleteMoviePart1 Obj = new DeleteMoviePart1();
        Obj.setVisible(true);
    }//GEN-LAST:event_B_DeleteMovieActionPerformed

    private void B_AddMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_AddMoviesActionPerformed
        
       AddMovieRecord Obj = new AddMovieRecord();
       Obj.setVisible(true);
        
        
    }//GEN-LAST:event_B_AddMoviesActionPerformed

    private void B_SearchMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_SearchMovieActionPerformed
        SearchMovie Obj = new SearchMovie();
        Obj.setVisible(true);
    }//GEN-LAST:event_B_SearchMovieActionPerformed

    private void B_AddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_AddCustomerActionPerformed
        AddNewCustomer Obj = new AddNewCustomer();
        Obj.setVisible(true);
    }//GEN-LAST:event_B_AddCustomerActionPerformed

    private void B_ExistingCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ExistingCustomerActionPerformed
        ExistingCustomer Obj = new ExistingCustomer();
        Obj.setVisible(true);
    }//GEN-LAST:event_B_ExistingCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_AddCustomer;
    private javax.swing.JButton B_AddMovies;
    private javax.swing.JButton B_DeleteCustomer;
    private javax.swing.JButton B_DeleteMovie;
    private javax.swing.JButton B_EditMovie;
    private javax.swing.JButton B_ExistingCustomer;
    private javax.swing.JButton B_SearchMovie;
    private javax.swing.JButton B_ShowMovies;
    private javax.swing.JButton Exit_Button;
    private javax.swing.JLabel L_CustomerArea;
    private javax.swing.JLabel L_MovieArea;
    private javax.swing.JPanel P_Head;
    private javax.swing.JPanel P_Left;
    private javax.swing.JPanel P_Right;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
